---
- hosts: all
  gather_facts: no
  vars:
    on_state:
      "on": true
      "bri": 120
      "xy": [0.5701, 0.313]
  tasks:
  - name: Flash lights in phillips hue
  - uri:
      url: "http://10.0.6.10/api/001788fffe4d9ae4/lights/{{item}}/state"
      method: PUT
      body: ' {{on_state|to_json}}'
    with_sequence: start=1 end=6

  - name: Create new Kibana dir
    copy: 
      src: pc_dashboard.ndjson
      dest: /Sort/
      owner: root
      group: root

  - name: Import Dashboard to Kibana
    uri:
      url: http://localhost:5601/api/saved_objects/_import?overwrite=true
      method: POST
      headers:
        Content-Type: "application/json; charset=utf-8"
        kbn-xsrf: true
      body_format: json
      body: "pc_dashboard.ndjson"
      user: "elastic"
      password: "sheetsOnTheBed"
      force_basic_auth: yes