---
- hosts: all

  tasks:
  - name: Create new Kibana dir
    copy: 
      src: ansible_test_app 
      dest: /tmp/
      owner: root
      group: root

  - name: install example application
    copy: 
      src: ansible_test_app 
      dest: /tmp/
      owner: root
      group: root

  - name: install example application
    copy: 
      src: ansible_test_app 
      dest: /tmp/
      owner: root
      group: root
